// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need the direct (non-pooled) connection. The Supabase ↔ Vercel
    // integration exposes it as POSTGRES_URL_NON_POOLING; local dev uses
    // DIRECT_URL from .env. Prefer the integration var, fall back to local.
    url:
      process.env["POSTGRES_URL_NON_POOLING"] ?? process.env["DIRECT_URL"],
  },
});
